### ISSUE TITLE
Support {{ NAMESPACE }} templating

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/thoughts-and-prayers#49]
Currently we have

`11-create-authentication-classes.yaml`
```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestStep
metadata:
  name: create-auth-class
commands:
  # We need to replace $NAMESPACE (by KUTTL) in the create-authentication-classes.yaml(.j2)
  # FIXME: Many tests use envsubst, which is better
  - script: eval "echo \"$(cat create-authentication-classes.yaml)\"" | kubectl apply -f -
```
`create-authentication-classes.yaml`
```yaml
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: oidc-$NAMESPACE
spec:
  provider:
    oidc:
      hostname: keycloak.$NAMESPACE.svc.cluster.local
      port: 8443
      rootPath: /realms/stackable
      scopes:
        - openid
      principalClaim: preferred_username
      tls:
        verification:
          server:
            caCert:
              secretClass: tls
```

Which is very stupid. Ideally you could just write something like {{ NAMESPACE }} and get that templated (by either beku or kuttl)
